apiVersion: v1
kind: Secret
metadata:
  name: huskyci-api-token-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: kubernetes.io/service-account-token
