---
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "huskyci-api.fullname" . }}-api-token
    namespace: {{ .Values.namespace }}
    annotations:
      kubernetes.io/service-account.name: {{ include "huskyci-api.serviceAccountName" . }}
type: kubernetes.io/service-account-token
