apiVersion: v1
kind: Service
metadata:
  name: {{ include "huskyci-api.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "huskyci-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "huskyci-api.selectorLabels" . | nindent 4 }}
